-- 0009 — cold-start NL ingredient lexicon (spec §21, plan/05 WS2).
-- item_normalised = canonical Dutch cooking term; aliases cover recipe spellings,
-- plurals and EN equivalents; aisle_group_id per 0005 taxonomy. Curated seed —
-- the E5 learning loop grows it from user corrections.

INSERT INTO catalog.ingredient_lexicon (item_normalised, aliases, default_unit, aisle_group_id, is_seed) VALUES
-- groente & fruit (1)
('ui', '{uien,gele ui,gewone ui,onion,onions}', 'stuks', 1, true),
('rode ui', '{rode uien,red onion}', 'stuks', 1, true),
('sjalot', '{sjalotten,sjalotje,shallot}', 'stuks', 1, true),
('knoflook', '{knoflookteen,teentje knoflook,knoflookteentjes,garlic}', 'stuks', 1, true),
('bosui', '{lente-ui,lenteui,lente ui,bosuitjes,spring onion,green onion,scallion}', 'stuks', 1, true),
('prei', '{preien,leek}', 'stuks', 1, true),
('tomaat', '{tomaten,tomatoes}', 'stuks', 1, true),
('cherrytomaat', '{cherrytomaten,cherrytomaatjes,snoeptomaten,kerstomaatjes,cherry tomatoes}', 'g', 1, true),
('trostomaat', '{trostomaten}', 'stuks', 1, true),
('paprika', '{paprikas,rode paprika,gele paprika,groene paprika,bell pepper}', 'stuks', 1, true),
('courgette', '{courgettes,zucchini}', 'stuks', 1, true),
('aubergine', '{aubergines,eggplant}', 'stuks', 1, true),
('broccoli', '{}', 'g', 1, true),
('bloemkool', '{cauliflower}', 'stuks', 1, true),
('spinazie', '{verse spinazie,spinach}', 'g', 1, true),
('boerenkool', '{kale}', 'g', 1, true),
('andijvie', '{}', 'g', 1, true),
('sla', '{kropsla,ijsbergsla,lettuce}', 'stuks', 1, true),
('rucola', '{arugula,raketsla}', 'g', 1, true),
('veldsla', '{}', 'g', 1, true),
('komkommer', '{komkommers,cucumber}', 'stuks', 1, true),
('wortel', '{wortels,wortelen,worteltjes,winterpeen,bospeen,carrot,carrots}', 'g', 1, true),
('aardappel', '{aardappelen,aardappels,potatoes}', 'kg', 1, true),
('kruimige aardappel', '{kruimige aardappelen,kruimig kokende aardappelen}', 'kg', 1, true),
('vastkokende aardappel', '{vastkokende aardappelen}', 'kg', 1, true),
('zoete aardappel', '{zoete aardappelen,zoete aardappels,bataat,sweet potato}', 'g', 1, true),
('krieltjes', '{kriel,krieltje}', 'g', 1, true),
('champignon', '{champignons,kastanjechampignons,mushrooms,paddenstoelen}', 'g', 1, true),
('citroen', '{citroenen,lemon}', 'stuks', 1, true),
('limoen', '{limoenen,lime}', 'stuks', 1, true),
('appel', '{appels,appelen,apple}', 'stuks', 1, true),
('banaan', '{bananen,banana}', 'stuks', 1, true),
('avocado', '{avocados,avocaado}', 'stuks', 1, true),
('gember', '{verse gember,gemberwortel,ginger}', 'g', 1, true),
('rode peper', '{rode pepers,spaanse peper,chilipeper,red chili}', 'stuks', 1, true),
('pompoen', '{flespompoen,butternut,pumpkin}', 'stuks', 1, true),
('venkel', '{venkelknol,fennel}', 'stuks', 1, true),
('bleekselderij', '{selderij,stengelselderij,celery}', 'stuks', 1, true),
('bimi', '{broccolini}', 'g', 1, true),
('sperzieboon', '{sperziebonen,haricots verts,groene bonen}', 'g', 1, true),
('peultjes', '{sugar snaps,sugarsnaps}', 'g', 1, true),
('mais', '{maiskolf,suikermais,corn}', 'stuks', 1, true),
('rode biet', '{bieten,bietjes,rode bieten,beetroot}', 'g', 1, true),
('pastinaak', '{parsnip}', 'stuks', 1, true),
('knolselderij', '{celeriac}', 'stuks', 1, true),
('witlof', '{witlofstronkjes}', 'stuks', 1, true),
('spitskool', '{}', 'stuks', 1, true),
('rodekool', '{rode kool}', 'g', 1, true),
('witte kool', '{wittekool}', 'stuks', 1, true),
('chinese kool', '{}', 'stuks', 1, true),
('paksoi', '{pak choi,bok choy}', 'stuks', 1, true),
('taugé', '{tauge,beansprouts}', 'g', 1, true),
('radijs', '{radijsjes,radishes}', 'g', 1, true),
('mango', '{mangos}', 'stuks', 1, true),
('sinaasappel', '{sinaasappels,sinaasappelen,orange}', 'stuks', 1, true),
('blauwe bes', '{blauwe bessen,blueberries}', 'g', 1, true),
('aardbei', '{aardbeien,strawberries}', 'g', 1, true),
('framboos', '{frambozen,raspberries}', 'g', 1, true),
('druiven', '{druif,grapes}', 'g', 1, true),
('verse koriander', '{koriander vers,cilantro}', 'bosje', 1, true),
('verse peterselie', '{peterselie vers,platte peterselie,krulpeterselie,parsley}', 'bosje', 1, true),
('verse basilicum', '{basilicum vers,basil}', 'bosje', 1, true),
('verse munt', '{munt,mint}', 'bosje', 1, true),
('bieslook', '{chives}', 'bosje', 1, true),
('verse dille', '{dille,dill}', 'bosje', 1, true),
('verse tijm', '{tijm vers,thyme vers}', 'bosje', 1, true),
('verse rozemarijn', '{rozemarijn vers,rosemary}', 'bosje', 1, true),
-- zuivel & eieren (2)
('melk', '{volle melk,milk}', 'ml', 2, true),
('halfvolle melk', '{}', 'ml', 2, true),
('karnemelk', '{buttermilk}', 'ml', 2, true),
('slagroom', '{room,heavy cream,whipping cream}', 'ml', 2, true),
('kookroom', '{cooking cream}', 'ml', 2, true),
('creme fraiche', '{crème fraîche,zure room,sour cream}', 'g', 2, true),
('yoghurt', '{naturel yoghurt,yogurt}', 'ml', 2, true),
('griekse yoghurt', '{greek yogurt,yoghurt griekse stijl}', 'g', 2, true),
('kwark', '{magere kwark,quark}', 'g', 2, true),
('boter', '{margarine,butter}', 'g', 2, true),
('roomboter', '{ongezouten roomboter,unsalted butter}', 'g', 2, true),
('ei', '{eieren,eitjes,eggs,egg}', 'stuks', 2, true),
('kokosmelk', '{coconut milk,santen}', 'ml', 9, true),
-- kaas & vleeswaren (5)
('geraspte kaas', '{kaas geraspt,grated cheese}', 'g', 5, true),
('jonge kaas', '{jong belegen kaas,goudse kaas}', 'g', 5, true),
('oude kaas', '{}', 'g', 5, true),
('parmezaanse kaas', '{parmezaan,parmigiano,grana padano,parmesan}', 'g', 5, true),
('mozzarella', '{buffelmozzarella,bolletje mozzarella}', 'stuks', 5, true),
('feta', '{witte kaas}', 'g', 5, true),
('geitenkaas', '{goat cheese}', 'g', 5, true),
('mascarpone', '{}', 'g', 5, true),
('roomkaas', '{monchou,cream cheese,zuivelspread}', 'g', 5, true),
('halloumi', '{grillkaas}', 'g', 5, true),
('spekreepjes', '{spekblokjes,spekjes,ontbijtspek,bacon}', 'g', 5, true),
('chorizo', '{}', 'g', 5, true),
('ham', '{achterham,beenham}', 'g', 5, true),
('salami', '{}', 'g', 5, true),
-- vlees & vis (3)
('kipfilet', '{kipfilets,kippenborst,chicken breast}', 'g', 3, true),
('kippendij', '{kippendijen,kipdijfilet,dijfilet,chicken thighs}', 'g', 3, true),
('gehakt', '{half-om-half gehakt,half om half,minced meat}', 'g', 3, true),
('rundergehakt', '{mager rundergehakt,ground beef}', 'g', 3, true),
('kipgehakt', '{}', 'g', 3, true),
('biefstuk', '{steak,kogelbiefstuk}', 'g', 3, true),
('rundvlees', '{riblappen,sukadelappen,stoofvlees,beef}', 'g', 3, true),
('varkenshaas', '{pork tenderloin}', 'g', 3, true),
('speklap', '{speklappen}', 'g', 3, true),
('worst', '{braadworst,verse worst,rookworst}', 'stuks', 3, true),
('zalm', '{zalmfilet,salmon}', 'g', 3, true),
('kabeljauw', '{kabeljauwfilet,cod}', 'g', 3, true),
('witvis', '{pangasius,tilapia,koolvis}', 'g', 3, true),
('garnaal', '{garnalen,gamba,gambas,shrimp,prawns}', 'g', 3, true),
('tonijn', '{tonijn uit blik,tuna}', 'blik', 9, true),
('kipshoarma', '{shoarma}', 'g', 3, true),
('kipdrumstick', '{drumsticks,kippenpoten}', 'g', 3, true),
-- vega & plantaardig (4)
('tofu', '{tahoe,firm tofu}', 'g', 4, true),
('tempeh', '{tempe}', 'g', 4, true),
('vegetarisch gehakt', '{vega gehakt,plantaardig gehakt}', 'g', 4, true),
('vegaburger', '{vegetarische burger,plantaardige burger}', 'stuks', 4, true),
('falafel', '{}', 'g', 4, true),
-- conserven, peulvruchten & soepen (9)
('kikkererwt', '{kikkererwten,chickpeas}', 'blik', 9, true),
('linzen', '{rode linzen,groene linzen,lentils}', 'g', 9, true),
('zwarte bonen', '{black beans}', 'blik', 9, true),
('kidneyboon', '{kidneybonen,rode nierbonen,kidney beans}', 'blik', 9, true),
('witte bonen', '{witte bonen in tomatensaus,cannellini}', 'blik', 9, true),
('doperwt', '{doperwten,erwten,peas}', 'g', 14, true),
('tomatenblokjes', '{gesneden tomaten,tomaten in blokjes,chopped tomatoes,diced tomatoes}', 'blik', 9, true),
('gezeefde tomaten', '{passata,tomatenpassata,gezeefde tomaat}', 'pak', 9, true),
('tomatenpuree', '{tomato paste,geconcentreerde tomatenpuree}', 'blik', 9, true),
('zongedroogde tomaat', '{zongedroogde tomaten,sundried tomatoes}', 'pot', 9, true),
('olijven', '{zwarte olijven,groene olijven,olives}', 'pot', 9, true),
('kappertjes', '{capers}', 'pot', 9, true),
('ansjovis', '{anchovies,ansjovisfilets}', 'blik', 9, true),
('augurk', '{augurken,pickles}', 'pot', 9, true),
('zilverui', '{zilveruitjes}', 'pot', 9, true),
('appelmoes', '{}', 'pot', 9, true),
('mais uit blik', '{blikje mais}', 'blik', 9, true),
-- pasta, rijst & wereldkeuken (8)
('rijst', '{witte rijst,zilvervliesrijst,rice}', 'g', 8, true),
('basmatirijst', '{basmati rijst,basmati}', 'g', 8, true),
('pandanrijst', '{jasmijnrijst,jasmine rice}', 'g', 8, true),
('risottorijst', '{arborio,risotto rijst}', 'g', 8, true),
('pasta', '{}', 'g', 8, true),
('spaghetti', '{}', 'g', 8, true),
('penne', '{}', 'g', 8, true),
('macaroni', '{}', 'g', 8, true),
('fusilli', '{}', 'g', 8, true),
('tagliatelle', '{}', 'g', 8, true),
('lasagnebladen', '{lasagnebladeren,lasagne bladen,lasagna sheets}', 'pak', 8, true),
('orzo', '{risoni}', 'g', 8, true),
('noedels', '{noodles,eiernoedels,udon,ramen}', 'g', 8, true),
('mie', '{bami,mienestjes}', 'g', 8, true),
('rijstnoedels', '{rice noodles,mihoen}', 'g', 8, true),
('couscous', '{}', 'g', 8, true),
('bulgur', '{}', 'g', 8, true),
('quinoa', '{}', 'g', 8, true),
('tortilla', '{tortillas,wraps,wrap}', 'stuks', 8, true),
('taco', '{tacos,tacoschelpen}', 'stuks', 8, true),
('sojasaus', '{soja saus,soy sauce,ketjap asin}', 'ml', 8, true),
('ketjap', '{ketjap manis,zoete sojasaus}', 'ml', 8, true),
('vissaus', '{fish sauce}', 'ml', 8, true),
('oestersaus', '{oyster sauce}', 'ml', 8, true),
('sriracha', '{hot sauce,chilisaus}', 'ml', 8, true),
('sambal', '{sambal oelek,sambal badjak}', 'tl', 8, true),
('currypasta', '{rode currypasta,groene currypasta,curry paste}', 'el', 8, true),
('miso', '{misopasta}', 'el', 8, true),
('tahin', '{tahini,sesampasta}', 'el', 8, true),
('kokosrasp', '{geraspte kokos}', 'g', 11, true),
('sesamzaad', '{sesamzaadjes,sesame seeds}', 'g', 8, true),
('sushirijst', '{sushi rijst}', 'g', 8, true),
-- kruiden, sauzen & olie (10)
('olijfolie', '{extra vierge olijfolie,olive oil}', 'ml', 10, true),
('zonnebloemolie', '{plantaardige olie,sunflower oil}', 'ml', 10, true),
('arachideolie', '{pindaolie,wokolie}', 'ml', 10, true),
('sesamolie', '{sesame oil}', 'ml', 10, true),
('azijn', '{natuurazijn,vinegar}', 'ml', 10, true),
('balsamicoazijn', '{balsamico,balsamic vinegar}', 'ml', 10, true),
('witte wijnazijn', '{wittewijnazijn,white wine vinegar}', 'ml', 10, true),
('rode wijnazijn', '{red wine vinegar}', 'ml', 10, true),
('mosterd', '{dijonmosterd,grove mosterd,mustard}', 'tl', 10, true),
('mayonaise', '{mayo}', 'el', 10, true),
('ketchup', '{tomatenketchup}', 'el', 10, true),
('honing', '{honey}', 'el', 10, true),
('ahornsiroop', '{maple syrup,esdoornsiroop}', 'el', 10, true),
('pindakaas', '{peanut butter}', 'el', 7, true),
('pesto', '{groene pesto,rode pesto}', 'pot', 10, true),
('hummus', '{houmous}', 'g', 10, true),
('bouillonblokje', '{bouillonblokjes,bouillontablet}', 'stuks', 10, true),
('groentebouillon', '{groentebouillonblokje,vegetable stock}', 'ml', 10, true),
('kippenbouillon', '{kippenbouillonblokje,chicken stock}', 'ml', 10, true),
('runderbouillon', '{beef stock}', 'ml', 10, true),
('visbouillon', '{fish stock}', 'ml', 10, true),
('zout', '{zeezout,salt}', 'snufje', 10, true),
('peper', '{zwarte peper,versgemalen peper,black pepper}', 'snufje', 10, true),
('paprikapoeder', '{gerookt paprikapoeder,paprika powder}', 'tl', 10, true),
('komijn', '{komijnpoeder,gemalen komijn,cumin,djinten}', 'tl', 10, true),
('kerriepoeder', '{kerrie,currypoeder,curry powder}', 'tl', 10, true),
('kurkuma', '{geelwortel,koenjit,turmeric}', 'tl', 10, true),
('kaneel', '{kaneelpoeder,cinnamon}', 'tl', 10, true),
('gemberpoeder', '{djahe}', 'tl', 10, true),
('korianderpoeder', '{gemalen koriander,ketoembar}', 'tl', 10, true),
('chilipoeder', '{chilivlokken,chili flakes,cayennepeper}', 'tl', 10, true),
('oregano', '{gedroogde oregano}', 'tl', 10, true),
('gedroogde tijm', '{tijm gedroogd}', 'tl', 10, true),
('laurierblad', '{laurier,laurierblaadjes,bay leaf}', 'stuks', 10, true),
('nootmuskaat', '{nutmeg}', 'snufje', 10, true),
('kruidnagel', '{cloves}', 'stuks', 10, true),
('kardemom', '{cardamom}', 'tl', 10, true),
('garam masala', '{}', 'tl', 10, true),
('italiaanse kruiden', '{provencaalse kruiden}', 'tl', 10, true),
('vanillesuiker', '{}', 'zakje', 11, true),
('vanille-extract', '{vanille extract,vanilla extract}', 'tl', 11, true),
-- bakken & zoet (11)
('bloem', '{tarwebloem,patentbloem,flour}', 'g', 11, true),
('zelfrijzend bakmeel', '{self-raising flour}', 'g', 11, true),
('volkorenmeel', '{volkoren meel}', 'g', 11, true),
('maizena', '{maïzena,cornstarch}', 'el', 11, true),
('suiker', '{kristalsuiker,witte suiker,sugar}', 'g', 11, true),
('basterdsuiker', '{witte basterdsuiker,bruine basterdsuiker}', 'g', 11, true),
('rietsuiker', '{bruine suiker,brown sugar}', 'g', 11, true),
('poedersuiker', '{icing sugar}', 'g', 11, true),
('bakpoeder', '{baking powder}', 'tl', 11, true),
('baksoda', '{zuiveringszout,baking soda}', 'tl', 11, true),
('gist', '{gedroogde gist,verse gist,instant gist}', 'zakje', 11, true),
('pure chocolade', '{chocola puur,dark chocolate}', 'g', 11, true),
('melkchocolade', '{}', 'g', 11, true),
('cacaopoeder', '{cacao,cocoa}', 'el', 11, true),
('chocoladedruppels', '{chocolate chips}', 'g', 11, true),
-- brood & ontbijt (6/7)
('brood', '{wit brood,bruin brood,volkorenbrood}', 'stuks', 6, true),
('stokbrood', '{baguette}', 'stuks', 6, true),
('ciabatta', '{}', 'stuks', 6, true),
('pitabroodje', '{pita,pitabroodjes}', 'stuks', 6, true),
('naanbrood', '{naan}', 'stuks', 6, true),
('turks brood', '{}', 'stuks', 6, true),
('hamburgerbroodje', '{hamburgerbroodjes,briochebroodje}', 'stuks', 6, true),
('paneermeel', '{panko,breadcrumbs}', 'g', 11, true),
('havermout', '{oats,havervlokken}', 'g', 7, true),
('muesli', '{granola,cruesli}', 'g', 7, true),
-- chips & noten (13)
('pinda', '{pindas,ongezouten pindas,peanuts}', 'g', 13, true),
('cashewnoot', '{cashewnoten,cashews}', 'g', 13, true),
('walnoot', '{walnoten,walnuts}', 'g', 13, true),
('amandel', '{amandelen,amandelschaafsel,almonds}', 'g', 13, true),
('hazelnoot', '{hazelnoten,hazelnuts}', 'g', 13, true),
('pistache', '{pistachenoten,pistachios}', 'g', 13, true),
('pijnboompit', '{pijnboompitten,pine nuts}', 'g', 13, true),
('zonnebloempit', '{zonnebloempitten}', 'g', 13, true),
('pompoenpit', '{pompoenpitten}', 'g', 13, true),
-- diepvries (14)
('bladerdeeg', '{roomboterbladerdeeg,puff pastry}', 'pak', 14, true),
('filodeeg', '{filo,phyllo}', 'pak', 14, true),
('diepvriesspinazie', '{spinazie diepvries}', 'g', 14, true),
('sojaboontjes', '{edamame}', 'g', 14, true),
('friet', '{frites,patat}', 'g', 14, true),
-- dranken (15/17)
('witte wijn', '{droge witte wijn,white wine}', 'ml', 17, true),
('rode wijn', '{red wine}', 'ml', 17, true),
('bier', '{pils,beer}', 'ml', 17, true),
('appelsap', '{}', 'ml', 15, true),
('sinaasappelsap', '{jus dorange,orange juice}', 'ml', 15, true)
ON CONFLICT (item_normalised) DO NOTHING;
